### ISSUE TITLE
markerbeforedelete Event return an error

### ISSUE THREAD

**Issue by anounbobo** [ailon/markerjs2#94]
I tried to add an event listener on markerbeforedelete but I got an error message:

`Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at Proxy.t2.addEventListener (Events.ts:214:47)
    at Proxy.t2.addEventListener (MarkerArea.ts:1616:25)`

Here is the code:

`    this.markerArea.addEventListener('markerbeforedelete ', (event) => {
      event.preventDefault();
    });`

**Comment by anounbobo** [comment]
It was an issue with my code.
